version: '3.8' # Specify compose file version

services:
  backend:
    container_name: trainer_backend_dev # Optional: name the container
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
      target: dev # Build the 'dev' stage by default for 'up' command
    ports:
      # Map host port 3001 to container port 3001
      - "3001:3001"
    env_file:
      # Load environment variables from the .env file
      - .env
    volumes:
      # Mount local files for development, but use docker volume for node_modules
      - .:/app
      - backend_node_modules:/app/node_modules
    # Keep the container running even if the entry command exits (useful for exec)
    stdin_open: true
    tty: true
    # Run our comprehensive dependency fixer before starting the app
    command: >
      /bin/sh -c '
        echo "Running comprehensive dependency fixer..." &&
        chmod +x /app/fix-dependencies.sh &&
        /app/fix-dependencies.sh &&
        node server.js
      '

volumes:
  # Named volume for node_modules to persist between container restarts
  backend_node_modules:
