---
config:
  layout: dagre
---
flowchart TB
 subgraph one["Profile Review/Edit - Load existing data & complete missing"]
        B2@{ label: "'Personal Information' tab (pre-filled or empty)" }
        B1["/profile"]
        B3@{ label: "'Physical Measurements' tab (pre-filled or empty)" }
        B4@{ label: "'Fitness Information' tab (pre-filled or empty)" }
        B5@{ label: "'Equipment & Preferences' tab (pre-filled or empty)" }
        B6@{ label: "Complete missing info & click 'Save Profile'" }
  end
 subgraph two["Finish to Dashboard"]
        C1["/dashboard"]
        C2@{ label: "/dashboard should have navbar that has a link back to /profile" }
        C3["click 'Profile' link"]
  end
    A1["Landing Page (/)"] --> A2{"Click"}
    A2 --> A3@{ label: "'Login'" }
    A3 -- Redirect --> A4["/login"]
    A4 --> A5["Fill in email & password"]
    A5 --> A6@{ label: "Click 'Sign in'" }
    A6 -- Check Profile Status --> A7{"Profile Complete?"}
    A7 -- Yes: Redirect to --> C1
    A7 -- No: Redirect to --> B1
    B1 -.-> B2 & B3 & B4 & B5
    B1 --> B6
    B6 -- Redirect to --> C1
    C1 --> C2
    C2 --> C3
    C3 -- Redirect to: --> B1
    B2@{ shape: sl-rect}
    B1@{ shape: doc}
    B3@{ shape: sl-rect}
    B4@{ shape: sl-rect}
    B5@{ shape: sl-rect}
    B6@{ shape: sl-rect}
    C1@{ shape: doc}
    C2@{ shape: display}
    C3@{ shape: sl-rect}
    A1@{ shape: doc}
    A3@{ shape: rounded}
    A4@{ shape: doc}
    A5@{ shape: sl-rect}
    A6@{ shape: sl-rect}
    A7@{ shape: diamond}
