---
config:
  layout: dagre
---
flowchart TB
 subgraph one["Create Profile"]
        B2@{ label: "Fill out 'Personal Information' tab" }
        B1["/profile/create"]
        B3@{ label: "Fill out 'Physical Measurements' tab" }
        B4@{ label: "Fill out 'Fitness Information' tab" }
        B5@{ label: "Fill out 'Equipment & Preferences' tab" }
  end
 subgraph two["Finish to Dashboard"]
        C1["/profile"]
        C2@{ label: "Verify profile info & click 'Save Profile'" }
        C3["/dashboard"]
  end
    A1["Landing Page (/)"] --> A2{"Click"}
    A2 --> A3@{ label: "'Sign Up' OR 'Get Started'" }
    A3 -- Redirect --> A4["/auth/signup"]
    A4 --> A5["Fill in name, email & password"]
    A5 --> A6@{ label: "Click 'Create Account'" }
    A6 -- Redirect --> B1
    B1 -.-> B2 & B3 & B4 & B5
    B2 -- Click 'Next >' --> B3
    B3 -- Click 'Next >' --> B4
    B4 -- Click 'Next >' --> B5
    B5 -- Click 'Create Profile' & Redirect ----> C1
    C1 --> C2
    C2 --> C3
    B2@{ shape: sl-rect}
    B1@{ shape: doc}
    B3@{ shape: sl-rect}
    B4@{ shape: sl-rect}
    B5@{ shape: sl-rect}
    C1@{ shape: doc}
    C2@{ shape: sl-rect}
    C3@{ shape: doc}
    A1@{ shape: doc}
    A3@{ shape: rounded}
    A4@{ shape: doc}
    A5@{ shape: sl-rect}
    A6@{ shape: sl-rect}

